# Seoul256 Dark Hard
# Author : EricHenry
# Original Creator: https://github.com/junegunn/seoul256.vim

inherits = "seoul256-dark"

"ui.background" = { bg = "gray1" }
"ui.gutter" = { bg = "gray2" }
"ui.cursorline.primary" = { bg = "gray" }
"ui.gutter.selected" = { bg = "gray" }
"ui.linenr.selected" = { bg = "gray", fg = "magenta", modifiers = ["bold"] }
